name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  go_router: ^17.0.1
  intl: ^0.20.2
  loading_overlay: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.jpg

flutter_launcher_icons:
  android: true
  image_path: "assets/app_logo.jpg"